/* USB peripheral bring-up for the STM32G0B1 without a crystal:
 * USB runs from HSI48, trimmed by the CRS against the host's 1 kHz SOF. */
#include "main.h"
#include "tusb.h"

void usb_hw_init(void)
{
  RCC_OscInitTypeDef osc = {0};
  osc.OscillatorType = RCC_OSCILLATORTYPE_HSI48;
  osc.HSI48State = RCC_HSI48_ON;
  HAL_RCC_OscConfig(&osc);

  RCC_PeriphCLKInitTypeDef clk = {0};
  clk.PeriphClockSelection = RCC_PERIPHCLK_USB;
  clk.UsbClockSelection = RCC_USBCLKSOURCE_HSI48;
  HAL_RCCEx_PeriphCLKConfig(&clk);

  __HAL_RCC_CRS_CLK_ENABLE();
  RCC_CRSInitTypeDef crs = {0};
  crs.Prescaler = RCC_CRS_SYNC_DIV1;
  crs.Source = RCC_CRS_SYNC_SOURCE_USB;
  crs.Polarity = RCC_CRS_SYNC_POLARITY_RISING;
  crs.ReloadValue = __HAL_RCC_CRS_RELOADVALUE_CALCULATE(48000000, 1000);
  crs.ErrorLimitValue = 34;
  crs.HSI48CalibrationValue = 32;
  HAL_RCCEx_CRSConfig(&crs);

  __HAL_RCC_PWR_CLK_ENABLE();
  HAL_PWREx_EnableVddUSB();
  __HAL_RCC_USB_CLK_ENABLE();
}

/* USB interrupts go straight to TinyUSB; this handler is not generated by CubeMX
 * as long as the USB peripheral stays disabled in the .ioc. */
void USB_UCPD1_2_IRQHandler(void)
{
  tud_int_handler(BOARD_TUD_RHPORT);
}

uint32_t tusb_time_millis_api(void)
{
  return HAL_GetTick();
}
